name: app_links_example
description: Demonstrates how to use the app_links plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  app_links: ^6.1.3

  ffi: ^2.1.0
  win32: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # linter rules (https://pub.dev/packages/flutter_lints)
  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
